version: 1
root:
  handlers: ["stdout"]
  level: DEBUG
loggers:
  "apscheduler.scheduler":
    level: WARN
  "apscheduler.executors.default":
    level: WARN
  "main":
    level: INFO
handlers:
  stdout:
    formatter: standard
    class: logging.StreamHandler
    level: DEBUG
formatters:
  standard:
    format: "%(levelname)-8s | %(asctime)s | %(threadName)-25s | %(name)s: %(message)s"
